import fs from "node:fs";
import fsp from "node:fs/promises";
import path from "node:path";
import crypto from "node:crypto";
import { execFile } from "node:child_process";
import { promisify } from "node:util";

const execFileAsync = promisify(execFile);

const JUNK_DIR_INFO: Record<string, { label: string; hint: string }> = {
  node_modules: { label: "node_modules", hint: "npm/yarn/pnpm install to restore" },
  ".venv": { label: "Python venv", hint: "recreate with python -m venv .venv" },
  venv: { label: "Python venv", hint: "recreate with python -m venv venv" },
  __pycache__: { label: "Python bytecode cache", hint: "regenerated automatically" },
  ".next": { label: "Next.js build cache", hint: "regenerated by next dev/build" },
  ".nuxt": { label: "Nuxt build cache", hint: "regenerated by nuxt dev/build" },
  ".turbo": { label: "Turborepo cache", hint: "regenerated automatically" },
  ".parcel-cache": { label: "Parcel cache", hint: "regenerated automatically" },
  ".pytest_cache": { label: "Pytest cache", hint: "regenerated automatically" },
  coverage: { label: "Test coverage report", hint: "regenerated by your test runner" },
  dist: { label: "Build output", hint: "regenerated by your build command" },
  build: { label: "Build output", hint: "regenerated by your build command" },
  target: { label: "Rust/Cargo build output", hint: "regenerated by cargo build" },
  ".cache": { label: "Generic cache", hint: "regenerated automatically" },
};

export const JUNK_DIR_NAMES = new Set(Object.keys(JUNK_DIR_INFO));
const ALWAYS_SKIP_DIR_NAMES = new Set([".git"]);
const MAX_DEPTH = 14;

export interface JunkEntry {
  path: string;
  name: string;
  label: string;
  hint: string;
  sizeBytes: number;
  mtimeMs: number;
}

export async function duSizeBytes(targetPath: string): Promise<number> {
  try {
    const { stdout } = await execFileAsync("du", ["-sk", targetPath], {
      timeout: 30_000,
      maxBuffer: 1024 * 1024,
    });
    const kb = parseInt(stdout.trim().split(/\s+/)[0], 10);
    return Number.isFinite(kb) ? kb * 1024 : 0;
  } catch {
    return 0;
  }
}

/** Finds regenerable build/dependency junk, without descending into matches (their size is summed as a whole). */
export async function findDevJunk(root: string): Promise<JunkEntry[]> {
  const found: JunkEntry[] = [];

  async function walk(dir: string, depth: number) {
    if (depth > MAX_DEPTH) return;
    let entries: fs.Dirent[];
    try {
      entries = await fsp.readdir(dir, { withFileTypes: true });
    } catch {
      return;
    }

    for (const entry of entries) {
      if (entry.isSymbolicLink() || !entry.isDirectory()) continue;
      if (ALWAYS_SKIP_DIR_NAMES.has(entry.name)) continue;

      const full = path.join(dir, entry.name);

      if (JUNK_DIR_NAMES.has(entry.name)) {
        const [sizeBytes, stat] = await Promise.all([duSizeBytes(full), fsp.stat(full).catch(() => null)]);
        const info = JUNK_DIR_INFO[entry.name];
        found.push({
          path: full,
          name: entry.name,
          label: info.label,
          hint: info.hint,
          sizeBytes,
          mtimeMs: stat?.mtimeMs ?? 0,
        });
        continue;
      }

      await walk(full, depth + 1);
    }
  }

  await walk(root, 0);
  return found.sort((a, b) => b.sizeBytes - a.sizeBytes);
}

export interface FileEntry {
  path: string;
  sizeBytes: number;
  mtimeMs: number;
}

export interface DuplicateGroup {
  sizeBytes: number;
  paths: string[];
}

export interface ReportResult {
  largestFiles: FileEntry[];
  duplicateGroups: DuplicateGroup[];
  scannedFileCount: number;
  totalBytes: number;
}

const MAX_LARGEST_FILES = 50;
// Files bigger than this are still shown under "largest files" but skipped
// for duplicate hashing — hashing multi-GB files on every scan isn't worth it.
const MAX_HASH_BYTES = 500 * 1024 * 1024;

async function partialHash(filePath: string, bytes = 65536): Promise<string> {
  const fd = await fsp.open(filePath, "r");
  try {
    const buf = Buffer.alloc(bytes);
    const { bytesRead } = await fd.read(buf, 0, bytes, 0);
    return crypto.createHash("sha256").update(buf.subarray(0, bytesRead)).digest("hex");
  } finally {
    await fd.close();
  }
}

function fullHash(filePath: string): Promise<string> {
  return new Promise((resolve, reject) => {
    const hash = crypto.createHash("sha256");
    const stream = fs.createReadStream(filePath);
    stream.on("data", (chunk) => hash.update(chunk));
    stream.on("end", () => resolve(hash.digest("hex")));
    stream.on("error", reject);
  });
}

/** Largest files + exact-duplicate groups under `root`, skipping the same junk dirs findDevJunk knows about. */
export async function scanReport(root: string): Promise<ReportResult> {
  const files: FileEntry[] = [];

  async function walk(dir: string, depth: number) {
    if (depth > MAX_DEPTH) return;
    let entries: fs.Dirent[];
    try {
      entries = await fsp.readdir(dir, { withFileTypes: true });
    } catch {
      return;
    }
    for (const entry of entries) {
      if (entry.isSymbolicLink()) continue;
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        if (ALWAYS_SKIP_DIR_NAMES.has(entry.name) || JUNK_DIR_NAMES.has(entry.name)) continue;
        await walk(full, depth + 1);
      } else if (entry.isFile()) {
        const stat = await fsp.stat(full).catch(() => null);
        if (stat) files.push({ path: full, sizeBytes: stat.size, mtimeMs: stat.mtimeMs });
      }
    }
  }

  await walk(root, 0);

  const totalBytes = files.reduce((sum, f) => sum + f.sizeBytes, 0);
  const largestFiles = [...files].sort((a, b) => b.sizeBytes - a.sizeBytes).slice(0, MAX_LARGEST_FILES);

  const bySize = new Map<number, FileEntry[]>();
  for (const f of files) {
    if (f.sizeBytes === 0) continue;
    const list = bySize.get(f.sizeBytes) ?? [];
    list.push(f);
    bySize.set(f.sizeBytes, list);
  }

  const duplicateGroups: DuplicateGroup[] = [];
  for (const [sizeBytes, group] of bySize) {
    if (group.length < 2 || sizeBytes > MAX_HASH_BYTES) continue;

    const byPartial = new Map<string, FileEntry[]>();
    for (const f of group) {
      const ph = await partialHash(f.path).catch(() => null);
      if (!ph) continue;
      const list = byPartial.get(ph) ?? [];
      list.push(f);
      byPartial.set(ph, list);
    }

    for (const candidates of byPartial.values()) {
      if (candidates.length < 2) continue;
      const byFull = new Map<string, string[]>();
      for (const f of candidates) {
        const fh = await fullHash(f.path).catch(() => null);
        if (!fh) continue;
        const list = byFull.get(fh) ?? [];
        list.push(f.path);
        byFull.set(fh, list);
      }
      for (const paths of byFull.values()) {
        if (paths.length >= 2) duplicateGroups.push({ sizeBytes, paths });
      }
    }
  }

  duplicateGroups.sort((a, b) => b.sizeBytes * b.paths.length - a.sizeBytes * a.paths.length);

  return { largestFiles, duplicateGroups, scannedFileCount: files.length, totalBytes };
}
